
modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/Rustic-Potatoes/Bountiful-Seals-NeoForge-1.21.1/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://api.modrinth.com/updates/bountiful-seals/forge_updates.json?neoforge=only"
displayURL="https://www.curseforge.com/minecraft/mc-mods/bountiful-seals"
logoFile="icon.png"
authors="RusticPotatoes"
description='''
Adds many arctic themed-features (such as seals!)
'''

[[dependencies."${mod_id}"]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
